//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01.AllEmployees
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHour
    {
        public int WorkHourEntryID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Task { get; set; }
        public int EntryHours { get; set; }
        public string EntryComments { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
